name: wrecksys
channels:
  - conda-forge
  - nvidia
  - nodefaults
dependencies:
  - python=3.10.12
  - pip
  - cuda-toolkit>=12.2
  - pandas=2.1.3
  - pyarrow=14.0.1
  - numpy
  - gdown
  - fsspec
  - tqdm
  - requests
  - aiohttp
  - pip:
    - tensorflow==2.15; sys_platform == "win32"
    - tensorflow[and-cuda]==2.15; sys_platform == "linux"
    - --extra-index-url https://pypi.nvidia.com